In [ ]:
# Instalation and import of libraries

%pip install pandas numpy matplotlib seaborn 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

1298.81s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: matplotlib in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.11.2)
Requirement already satisfied: seaborn in /usr/local/python/3.14.2/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
# load crucial data

players = pd.read_csv("../data/players.csv")
player_injuries = pd.read_csv("../data/player_injuries.csv")
games = pd.read_csv("../data/games.csv")
appearances = pd.read_csv("../data/appearances.csv")
player_performances = pd.read_csv("../data/player_performances.csv")
transfers = pd.read_csv("../data/transfers.csv")

First step of finding players

In [ ]:
player_injuries.info()

<class 'pandas.DataFrame'>
RangeIndex: 143195 entries, 0 to 143194
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   player_id      143195 non-null  int64
 1   season_name    143195 non-null  str
 2   injury_reason  143195 non-null  str
 3   from_date      143173 non-null  str
 4   end_date       141672 non-null  str
 5   days_missed    143173 non-null  float64
 6   games_missed   143195 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 7.6 MB

In [ ]:
player_injuries.head()

,player_id,season_name,injury_reason,from_date,end_date,days_missed,games_missed
0,10,15/16,Hand injury,2016-04-19,2016-04-29,11.0,2
1,10,15/16,Thigh problems,2015-12-18,2015-12-31,14.0,1
2,10,15/16,Capsular injury,2015-11-11,2015-11-21,11.0,0
3,10,15/16,Rest,2015-11-04,2015-11-06,3.0,1
4,10,15/16,Hamstring injury,2015-08-20,2015-10-08,50.0,10

In [ ]:
# Definition of Meniscus injury 'mensicus...'
player_injuries.loc[
    player_injuries["injury_reason"].str.contains("meniscus", case=False, na=False),
    "injury_reason"
].unique()

<StringArray>
[             'Meniscus damage',                'Meniscus tear',
              'Meniscus injury', 'Tear of the lateral meniscus',
          'Meniscus irritation']
Length: 5, dtype: str

In [ ]:
# table of players with Meniscus injury 
meniscus_df = player_injuries[player_injuries['injury_reason'].isin(['Meniscus damage', 'Meniscus tear', 'Meniscus injury',
       'Tear of the lateral meniscus', 'Meniscus irritation'])].copy()
meniscus_df.shape

(1863, 7)

In [29]:
# change data type
meniscus_df["from_date"] = pd.to_datetime(meniscus_df["from_date"])
meniscus_df["end_date"] = pd.to_datetime(meniscus_df["end_date"])

In [ ]:
# Change table to proper dates
meniscus_dates = meniscus_df[
    meniscus_df["from_date"].between("2012-07-03", "2026-06-28")
].copy()

In [31]:
top5_ids = ["GB1", "ES1", "IT1", "L1", "FR1"]

player_top5 = (
    player_performances[
        player_performances["competition_id"].isin(top5_ids)
    ][["player_id", "season_name", "competition_id"]]
    .drop_duplicates()
)

In [32]:
meniscus_top5 = meniscus_dates.merge(
    player_top5,
    on=["player_id", "season_name"],
    how="inner"
)
meniscus_top5.head()

,player_id,season_name,injury_reason,from_date,end_date,days_missed,games_missed,competition_id
0,106987,22/23,Meniscus injury,2023-05-10,2023-06-15,37.0,5,GB1
1,106987,22/23,Meniscus injury,2023-05-10,2023-06-15,37.0,5,L1
2,1077175,24/25,Meniscus injury,2024-11-22,2025-04-08,138.0,19,IT1
3,108390,23/24,Meniscus tear,2024-04-01,2024-04-28,28.0,5,ES1
4,109038,14/15,Meniscus tear,2015-03-15,2015-09-24,194.0,18,IT1